//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NumberMagick.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaveNumber
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public Nullable<int> IdUser { get; set; }
        public string Descp { get; set; }
    
        public virtual User User { get; set; }
    }
}
